# Generated by Django 3.1.4 on 2021-01-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mrouter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('host', models.CharField(max_length=40)),
                ('user', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=50)),
                ('up_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
