# Generated by Django 3.1.4 on 2021-01-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0002_router'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
